name: Release json file

on:
  push:
    branches: [ main ]

jobs:

  release-github:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x
    - name: convert and publish 1.0.0
      run: dotnet fsi release/templates-to-json_v1.0.0.fsx
    - name: convert and publish 2.0.0
      run: dotnet fsi release/templates-to-json_v2.0.0.fsx
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Template Json"
        files: |
            templates-to-json/report.txt
            templates-to-json/templates.json
            templates-to-json/report_v2.0.0.txt
            templates-to-json/templates_v2.0.0.json
